services:
  postgresql:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - 8761:8761

  cliente-ms:
    build:
      context: ./cliente-ms
    environment:
      - DB_HOST_NAME=postgresql
      - EUREKA_HOST_NAME=discovery-server
    depends_on:
      - discovery-server
      - postgresql
