### Criar um novo emprestimo
POST http://localhost:8084/emprestimos
Content-Type: application/json

{
  "clienteId": 2,
  "itens": [
    {
      "produtoId": 1,
      "quantidade": 15
    },
    {
      "produtoId": 10,
      "quantidade": 3
    },
    {
      "produtoId": 7,
      "quantidade": 5
    },
    {
      "produtoId": 6,
      "quantidade": 1
    }
  ]
}

### Atualizar um emprestimo
PUT http://localhost:8084/emprestimos/2
Content-Type: application/json

{
  "clienteId": 4,
  "itens": [
    {
      "produtoId": 4,
      "quantidade": 4
    },
    {
      "produtoId": 1,
      "quantidade": 15
    }
  ]
}

### Realizar devolução de um empréstimo
PUT http://localhost:8084/emprestimos/4/devolucao

### Deletar um cliente
DELETE http://localhost:8084/emprestimos/2

### Listar todos os clientes paginado
GET http://localhost:8084/emprestimos

### Detalhar um cliente
GET http://localhost:8084/emprestimos/4