### Criar um novo cliente
POST http://localhost:8080/clientes
Content-Type: application/json

{
  "cpf": "58602874022",
  "nome": "Terezinha",
  "email": "terezinha@email.com",
  "telefone": "(47)9 123456-47",
  "endereco": {
    "cep": "12345678",
    "cidade": "Blumenau",
    "rua": "7 de setembro",
    "numero": "789C",
    "complemento": "",
    "bairro": "Centro",
    "estado": "SC",
    "pais": "Brasil"
  }
}

### Atualizar um cliente
PUT http://localhost:8080/clientes/7
Content-Type: application/json

{
  "cpf": "58602874022",
  "nome": "Terezinha",
  "email": "terezinha@email.com",
  "telefone": "(47)9 123456-47",
  "endereco": {
    "cep": "12345678",
    "cidade": "Blumenau",
    "rua": "7 de setembro",
    "numero": "789C",
    "complemento": "",
    "bairro": "Centro",
    "estado": "SC",
    "pais": "Brasil"
  }
}

### Deletar um cliente
DELETE http://localhost:8080/clientes/7

### Listar todos os clientes paginado
GET http://localhost:8080/clientes

### Detalhar um cliente
GET http://localhost:8080/clientes/3