server:
  port: ${PORT:8084}

spring:
  application:
    name: emprestimo-ms

  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME:localhost}:5432/jnmodas_gestao_emprestimo_ms_db
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka
